# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chen Zhu | YALA | Yet Another Legal Academic
author: Chen Zhu
email: c.w.zhu[at]bham.ac.uk
description:  This is YALA's website
theme: minima
header_pages:
  - about.md
  - publication.md
  - seminar.md
  - org-mode.md
  - concert.md


  # this means to ignore newlines until "baseurl:" Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog

url: "https://icaruszhu.github.io/"  # cz: 解决图片不显示问题 "会存现有些资源（最为常见的是图片加载不出来）加载不出来，那是因为路径问题，建议使用将需要在_config.yml设置的路径baseurl :; url :等置空" @ https://blog.csdn.net/qq_35495763/article/details/79945734
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: cwzhu
github_username:  icaruszhu

# Build settings
# markdown: kramdown

# exclude (added 28 May 2019)
# exclude: [Gemfile, Gemfile.lock, README.md, vendor, org, .hyde.el]


