
# Setup


locale:       "en"

title: Chen Wei Zhu
description:  Yet Another Legal Academic @ Birmingham Law School, UK
tagline: Yet Another Legal Academic | YALA
baseurl:      ""


author: Chen Zhu
email: c.w.zhu[at]bham.ac.uk


show_downloads: false
google_analytics:
theme: jekyll-theme-architect




# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
